package com.dilloney.speedrunnermod.client;

import com.dilloney.speedrunnermod.option.OptionsFileManager;
import com.dilloney.speedrunnermod.option.ModOptions;
import me.shedaniel.autoconfig.annotation.Config;
import me.shedaniel.clothconfig2.api.ConfigBuilder;
import me.shedaniel.clothconfig2.api.ConfigCategory;
import me.shedaniel.clothconfig2.api.ConfigEntryBuilder;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.MinecraftClient;
import net.minecraft.text.TranslatableText;

@Config(name = "speedrunnermod")
@Environment(EnvType.CLIENT)
public class ModOptionsScreen {

    public static ConfigBuilder getConfigBuilder() {

        ConfigBuilder builder = ConfigBuilder.create().setParentScreen(MinecraftClient.getInstance().currentScreen).setTitle(new TranslatableText("speedrunnermod.options"));

        ModOptions currentOptions = OptionsFileManager.get();

        ConfigEntryBuilder entryBuilder = builder.entryBuilder();

        builder.setSavingRunnable(() -> {
            OptionsFileManager.set(currentOptions);
        });

        ConfigCategory speedrunnermodoptions = builder.getOrCreateCategory(new TranslatableText("speedrunnermod.options.general"));
        ConfigCategory speedrunnermodclientoptions = builder.getOrCreateCategory(new TranslatableText("speedrunnermod.options.client"));
        ConfigCategory speedrunnermodworld = builder.getOrCreateCategory(new TranslatableText("speedrunnermod.options.world"));
        ConfigCategory speedrunnermodstructures = builder.getOrCreateCategory(new TranslatableText("speedrunnermod.options.structures_config"));
        ConfigCategory speedrunnermodinfo = builder.getOrCreateCategory(new TranslatableText("speedrunnermod.info"));

        speedrunnermodoptions.addEntry(entryBuilder.startIntSlider(new TranslatableText("option.speedrunnermod.mod_difficulty"), currentOptions.modDifficulty, 1, 4).setDefaultValue(1).setMin(1).setMax(4).setTooltip(new TranslatableText("option.speedrunnermod.mod_difficulty.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.modDifficulty = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.normal_mode"), currentOptions.normalMode).setDefaultValue(currentOptions.normalMode).setTooltip(new TranslatableText("option.speedrunnermod.normal_mode.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.normalMode = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.make_structures_more_common"), currentOptions.makeStructuresMoreCommon).setDefaultValue(currentOptions.makeStructuresMoreCommon).setTooltip(new TranslatableText("option.speedrunnermod.make_structures_more_common.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.makeStructuresMoreCommon = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.modified_world_generation"), currentOptions.modifiedWorldGeneration).setDefaultValue(currentOptions.modifiedWorldGeneration).setTooltip(new TranslatableText("option.speedrunnermod.modified_world_generation.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.modifiedWorldGeneration = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.modified_block_hardness_values"), currentOptions.modifiedBlockHardness).setDefaultValue(currentOptions.modifiedBlockHardness).setTooltip(new TranslatableText("option.speedrunnermod.modified_block_hardness_values.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.modifiedBlockHardness = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.modified_loot_tables"), currentOptions.modifiedLootTables).setDefaultValue(currentOptions.modifiedLootTables).setTooltip(new TranslatableText("option.speedrunnermod.modified_loot_tables.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.modifiedLootTables = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.kill_ghast_upon_fireball"), currentOptions.killGhastUponFireball).setDefaultValue(currentOptions.killGhastUponFireball).setTooltip(new TranslatableText("option.speedrunnermod.kill_ghast_upon_fireball.hover")).setSaveConsumer(newValue -> currentOptions.killGhastUponFireball = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.doom_mode"), currentOptions.doomMode).setDefaultValue(currentOptions.doomMode).setTooltip(new TranslatableText("option.speedrunnermod.doom_mode.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.doomMode = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.icarus_mode"), currentOptions.iCarusMode).setDefaultValue(currentOptions.iCarusMode).setTooltip(new TranslatableText("option.speedrunnermod.icarus_mode.hover")).setSaveConsumer(newValue -> currentOptions.iCarusMode = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.infini_pearl_mode"), currentOptions.infiniPearlMode).setDefaultValue(currentOptions.infiniPearlMode).setTooltip(new TranslatableText("option.speedrunnermod.infini_pearl_mode.hover")).setSaveConsumer(newValue -> currentOptions.infiniPearlMode = newValue).build());
        speedrunnermodoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.manhunt_mode"), currentOptions.manhuntMode).setDefaultValue(currentOptions.manhuntMode).setTooltip(new TranslatableText("option.speedrunnermod.manhunt_mode.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.manhuntMode = newValue).build());
        speedrunnermodclientoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.fog"), currentOptions.fog).setDefaultValue(currentOptions.fog).setTooltip(new TranslatableText("option.speedrunnermod.fog.hover")).setSaveConsumer(newValue -> currentOptions.fog = newValue).build());
        speedrunnermodclientoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.custom_textures"), currentOptions.customTextures).setDefaultValue(currentOptions.customTextures).setTooltip(new TranslatableText("option.speedrunnermod.custom_textures.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.customTextures = newValue).build());
        speedrunnermodclientoptions.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.advanced_mod_tooltips"), currentOptions.advancedModTooltips).setDefaultValue(currentOptions.advancedModTooltips).setTooltip(new TranslatableText("option.speedrunnermod.advanced_mod_tooltips.hover")).setSaveConsumer(newValue -> currentOptions.advancedModTooltips = newValue).build());
        speedrunnermodworld.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.stronghold_count"), currentOptions.strongholdCount).setDefaultValue(currentOptions.strongholdCount).setMin(64).setMax(256).setTooltip(new TranslatableText("option.speedrunnermod.stronghold_count.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.strongholdCount = newValue).build());
        speedrunnermodworld.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.stronghold.distance"), currentOptions.strongholdDistance).setDefaultValue(currentOptions.strongholdDistance).setMin(3).setMax(36).setTooltip(new TranslatableText("option.speedrunnermod.stronghold.distance.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.strongholdDistance = newValue).build());
        speedrunnermodworld.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.nether_ruined_portals"), currentOptions.netherRuinedPortals).setDefaultValue(currentOptions.netherRuinedPortals).setTooltip(new TranslatableText("option.speedrunnermod.nether_ruined_portals.hover")).requireRestart().setSaveConsumer(newValue -> currentOptions.netherRuinedPortals = newValue).build());
        speedrunnermodworld.addEntry(entryBuilder.startBooleanToggle(new TranslatableText("option.speedrunnermod.nether_portals_in_the_end"), currentOptions.netherPortalsInTheEnd).setDefaultValue(currentOptions.netherPortalsInTheEnd).setTooltip(new TranslatableText("option.speedrunnermod.nether_portals_in_the_end.hover")).setSaveConsumer(newValue -> currentOptions.netherPortalsInTheEnd = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.ruined_portal.spacing"), currentOptions.ruinedPortalSpacing).setDefaultValue(currentOptions.ruinedPortalSpacing).setMin(6).setMax(40).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.ruinedPortalSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.ruined_portal.separation"), currentOptions.ruinedPortalSeparation).setDefaultValue(currentOptions.ruinedPortalSeparation).setMin(3).setMax(15).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.ruinedPortalSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.village.spacing"), currentOptions.villageSpacing).setDefaultValue(currentOptions.villageSpacing).setMin(5).setMax(32).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.villageSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.village.separation"), currentOptions.villageSeparation).setDefaultValue(currentOptions.villageSeparation).setMin(3).setMax(12).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.villageSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.desert_pyramid.spacing"), currentOptions.desertPyramidSpacing).setDefaultValue(currentOptions.desertPyramidSpacing).setMin(8).setMax(32).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.desertPyramidSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.desert_pyramid.separation"), currentOptions.desertPyramidSeparation).setDefaultValue(currentOptions.desertPyramidSeparation).setMin(3).setMax(10).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.desertPyramidSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.igloo.spacing"), currentOptions.iglooSpacing).setDefaultValue(currentOptions.iglooSpacing).setMin(2).setMax(32).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.iglooSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.igloo.separation"), currentOptions.iglooSeparation).setDefaultValue(currentOptions.iglooSeparation).setMin(1).setMax(8).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.iglooSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.jungle_pyramid.spacing"), currentOptions.junglePyramidSpacing).setDefaultValue(currentOptions.iglooSpacing).setMin(3).setMax(32).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.junglePyramidSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.jungle_pyramid.separation"), currentOptions.junglePyramidSeparation).setDefaultValue(currentOptions.iglooSeparation).setMin(1).setMax(8).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.junglePyramidSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.swamp_hut.spacing"), currentOptions.swampHutSpacing).setDefaultValue(currentOptions.swampHutSpacing).setMin(2).setMax(32).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.swampHutSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.swamp_hut.separation"), currentOptions.swampHutSeparation).setDefaultValue(currentOptions.swampHutSeparation).setMin(1).setMax(8).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.swampHutSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.pillager_outpost.spacing"), currentOptions.pillagerOutpostSpacing).setDefaultValue(currentOptions.pillagerOutpostSpacing).setMin(8).setMax(32).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.pillagerOutpostSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.pillager_outpost.separation"), currentOptions.pillagerOutpostSeparation).setDefaultValue(currentOptions.pillagerOutpostSeparation).setMin(6).setMax(8).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.pillagerOutpostSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.monument.spacing"), currentOptions.monumentSpacing).setDefaultValue(currentOptions.monumentSpacing).setMin(5).setMax(32).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.monumentSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.monument.separation"), currentOptions.monumentSeparation).setDefaultValue(currentOptions.monumentSeparation).setMin(2).setMax(5).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.monumentSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.shipwreck.spacing"), currentOptions.shipwreckSpacing).setDefaultValue(currentOptions.shipwreckSpacing).setMin(6).setMax(24).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.shipwreckSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.shipwreck.separation"), currentOptions.shipwreckSeparation).setDefaultValue(currentOptions.shipwreckSeparation).setMin(2).setMax(10).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.shipwreckSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.ocean_ruin.spacing"), currentOptions.oceanRuinSpacing).setDefaultValue(currentOptions.oceanRuinSpacing).setMin(3).setMax(20).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.oceanRuinSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.ocean_ruin.separation"), currentOptions.oceanRuinSeparation).setDefaultValue(currentOptions.oceanRuinSeparation).setMin(2).setMax(8).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.oceanRuinSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.fortress.spacing"), currentOptions.fortressSpacing).setDefaultValue(currentOptions.fortressSpacing).setMin(4).setMax(27).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.fortressSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.fortress.separation"), currentOptions.fortressSeparation).setDefaultValue(currentOptions.fortressSeparation).setMin(2).setMax(10).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.fortressSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.bastion.spacing"), currentOptions.bastionSpacing).setDefaultValue(currentOptions.bastionSpacing).setMin(5).setMax(27).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.bastionSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.bastion.separation"), currentOptions.bastionSeparation).setDefaultValue(currentOptions.bastionSeparation).setMin(3).setMax(10).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.bastionSeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.end_city.spacing"), currentOptions.endCitySpacing).setDefaultValue(currentOptions.endCitySpacing).setMin(3).setMax(20).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.endCitySpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.end_city.separation"), currentOptions.endCitySeparation).setDefaultValue(currentOptions.endCitySeparation).setMin(1).setMax(11).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.endCitySeparation = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.mansion.spacing"), currentOptions.mansionSpacing).setDefaultValue(currentOptions.mansionSpacing).setMin(3).setMax(80).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.mansionSpacing = newValue).build());
        speedrunnermodstructures.addEntry(entryBuilder.startIntField(new TranslatableText("option.speedrunnermod.mansion.separation"), currentOptions.mansionSeparation).setDefaultValue(currentOptions.mansionSeparation).setMin(1).setMax(20).setTooltip(new TranslatableText("option.speedrunnermod.world.warning")).requireRestart().setSaveConsumer(newValue -> currentOptions.mansionSeparation = newValue).build());
        speedrunnermodinfo.addEntry(entryBuilder.startTextField(new TranslatableText("info.speedrunnermod.mod_version"), "v1.3.1 (August 22nd, 2021)").setTooltip(new TranslatableText("info.speedrunnermod.mod_version.hover")).build());
        speedrunnermodinfo.addEntry(entryBuilder.startTextField(new TranslatableText("info.speedrunnermod.wiki"), "https://sites.google.com/view/speedrunnermod/home").setTooltip(new TranslatableText("info.speedrunnermod.wiki.hover")).build());
        speedrunnermodinfo.addEntry(entryBuilder.startTextField(new TranslatableText("info.speedrunnermod.discord"), "https://discord.gg/Qu8utnCwkq").setTooltip(new TranslatableText("info.speedrunnermod.discord.hover")).build());
        speedrunnermodinfo.addEntry(entryBuilder.startTextField(new TranslatableText("info.speedrunnermod.curseforge"), "https://www.curseforge.com/minecraft/mc-mods/speedrunner-mod").setTooltip(new TranslatableText("info.speedrunnermod.curseforge.hover")).build());
        speedrunnermodinfo.addEntry(entryBuilder.startTextField(new TranslatableText("info.speedrunnermod.youtube"), "https://www.youtube.com/channel/UCNZVI8pFpzn-eXEZsyDEagg").setTooltip(new TranslatableText("info.speedrunnermod.youtube.hover")).build());
        speedrunnermodinfo.addEntry(entryBuilder.startTextField(new TranslatableText("info.speedrunnermod.twitch"), "https://www.twitch.tv/dilloney").setTooltip(new TranslatableText("info.speedrunnermod.twitch.hover")).build());
        return builder;
    }
}
